#!/usr/bin/env python3
"""Build graph-ready comparison tables from the scorecards in results/.

The harness writes one JSON scorecard per (system, suite) run. This collapses
the latest run per (system, suite, scope) into:

  - results/comparison.csv   — tidy long format (one row per metric), for plotting
  - results/COMPARISON.md    — a wide per-suite markdown table, for the eyeballs

"Scope" is read from each scorecard's config (e.g. titles=neutral, retrieval_only)
so a neutral-title CH run and a realistic-title CH run don't overwrite each other.

Usage:
    python3 scripts/export_table.py [--results DIR] [--metrics m1,m2,...]
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
from collections import OrderedDict

# Retrieval-quality metrics, in display order. Latency last (different unit).
DEFAULT_METRICS = [
    "recall@k",
    "ndcg@k",
    "mrr",
    "precision@k",
    "hit@k",
    "latency_ms_p50",
    "latency_ms_p95",
]


def _scope(card: dict) -> str:
    """A short label distinguishing runs of the same system+suite."""
    cfg = card.get("config") or {}
    bits = []
    if cfg.get("retrieval_only"):
        bits.append("retrieval")
    if "titles" in cfg:
        bits.append(f"titles={cfg['titles']}")
    if cfg.get("note"):
        bits.append(str(cfg["note"]))
    return ",".join(bits) or "default"


def _load_latest(results_dir: str, note: str | None = None) -> "OrderedDict[tuple[str, str, str], dict]":
    """Latest scorecard per (system, suite, scope), keyed by finished_at.

    When `note` is given, only scorecards whose config.note matches are kept —
    so a clean published table reflects exactly one sweep and doesn't mix a
    stale smoke run's numbers in with the real one.
    """
    latest: dict[tuple[str, str, str], dict] = {}
    for path in sorted(glob.glob(os.path.join(results_dir, "*.json"))):
        try:
            card = json.loads(open(path).read())
        except (ValueError, OSError):
            continue
        if "system" not in card or "suite" not in card:
            continue
        if note is not None and (card.get("config") or {}).get("note") != note:
            continue
        # Back-compat: pre-fix scorecards keyed nDCG as "ndcg@10"; alias to the
        # corrected "ndcg@k" so old and new runs share the column.
        m = card.get("metrics") or {}
        if "ndcg@k" not in m and "ndcg@10" in m:
            m["ndcg@k"] = m["ndcg@10"]
        key = (card["system"], card["suite"], _scope(card))
        cur = latest.get(key)
        if cur is None or str(card.get("finished_at", "")) > str(cur.get("finished_at", "")):
            latest[key] = card
    # Stable order: suite, then system.
    return OrderedDict(sorted(latest.items(), key=lambda kv: (kv[0][1], kv[0][0], kv[0][2])))


def export(results_dir: str, metrics: list[str], note: str | None = None) -> tuple[str, str]:
    cards = _load_latest(results_dir, note=note)

    # ── tidy CSV (long format) ──
    csv_path = os.path.join(results_dir, "comparison.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["suite", "system", "scope", "n_questions", "n_memories", "metric", "value"])
        for (system, suite, scope), card in cards.items():
            m = card.get("metrics", {})
            for metric in metrics:
                if metric in m:
                    w.writerow([
                        suite, system, scope,
                        card.get("n_questions", ""), card.get("n_memories", ""),
                        metric, round(float(m[metric]), 4),
                    ])

    # ── wide markdown, one table per suite ──
    def fmt(metric: str, val: float) -> str:
        if metric.startswith("latency"):
            return f"{val:.0f}ms"
        return f"{val * 100:.1f}%"

    suites: "OrderedDict[str, list]" = OrderedDict()
    for key, card in cards.items():
        suites.setdefault(key[1], []).append((key[0], key[2], card))

    lines = ["# Benchmark comparison", "", "_Retrieval-only (no LLM answer). Generated by `scripts/export_table.py`._", ""]
    headers = {
        "recall@k": "recall@k", "ndcg@k": "nDCG@k", "mrr": "MRR",
        "precision@k": "precision@k", "hit@k": "hit@k",
        "latency_ms_p50": "p50", "latency_ms_p95": "p95",
    }
    for suite, rows in suites.items():
        # Sort systems by recall@k desc (the headline ranking).
        rows.sort(key=lambda r: r[2].get("metrics", {}).get("recall@k", 0.0), reverse=True)
        sample = rows[0][2]
        lines.append(f"## {suite}  ·  {sample.get('n_questions','?')} questions")
        lines.append("")
        head = "| system | scope | " + " | ".join(headers.get(m, m) for m in metrics) + " |"
        sep = "| --- | --- | " + " | ".join("---" for _ in metrics) + " |"
        lines += [head, sep]
        for system, scope, card in rows:
            m = card.get("metrics", {})
            cells = [fmt(metric, float(m[metric])) if metric in m else "—" for metric in metrics]
            lines.append(f"| {system} | {scope} | " + " | ".join(cells) + " |")
        lines.append("")

    md_path = os.path.join(results_dir, "COMPARISON.md")
    open(md_path, "w").write("\n".join(lines))
    return csv_path, md_path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--metrics", default=",".join(DEFAULT_METRICS),
                    help="comma-separated metric keys in display order")
    ap.add_argument("--note", default=None,
                    help="only include scorecards with this config.note (e.g. 's2')")
    args = ap.parse_args()
    metrics = [m.strip() for m in args.metrics.split(",") if m.strip()]
    csv_path, md_path = export(args.results, metrics, note=args.note)
    print(f"wrote {csv_path}")
    print(f"wrote {md_path}")


if __name__ == "__main__":
    main()
